apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-consumer-scaler
  namespace: producer-consumer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kafka-consumer
  minReplicaCount: {{ .Values.minReplicas }}
  maxReplicaCount: {{ .Values.maxReplicas }}
  triggers:
    - type: apache-kafka
      metadata:
        bootstrapServers: {{ .Values.bootstrapServers | quote }}
        consumerGroup: {{ .Values.consumerGroup }}
        topic: {{ .Values.topic }}
        lagThreshold: "1"
        offsetResetPolicy: latest
        allowIdleConsumers: "true"
        awsRegion: {{ .Values.awsRegion | quote }}
      authenticationRef:
        name: keda-msk-trigger-auth
