apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-msk-trigger-auth
  namespace: producer-consumer
spec:
  podIdentity:
    provider: aws
  secretTargetRef:
    - parameter: sasl
      name: keda-msk-auth-secrets
      key: sasl
    - parameter: tls
      name: keda-msk-auth-secrets
      key: tls
